### ISSUE TITLE
Error: Delimiter not found in the file "\t" (False Error on VERY Long Fields)

### ISSUE THREAD

**Issue by mmartimo** [adaltas/node-csv-parse#145]
I have a simple test script:
```
  streamTest
  .pipe(csv.parse({ columns: true, auto_parse: false, delimiter: '\t' }))
  .on('data', (data) => {
    lineCount++;
    if (lineCount > 27100 ) {
      console.log(`${lineCount} (${data.GEOMETRY.length}): ${data.GEOMETRY}`);
    }
  })
```

I have a datafile that is producing the following output:
```

27101 (900): POLYGON ((-94.54188 33.31186, -94.5419 ...

27102 (992): POLYGON ((-94.5918 33.29107, -94.59171 ...

27103 (1238): POLYGON ((-94.5849 33.28622, -94.58478 ...

27104 (268): POLYGON ((-96.70757 33.04324, -96.70762 ...

27105 (1217): POLYGON ((-73.50145 45.86377, -73.50207 ...

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Delimiter not found in the file "\t"
    at Error (native)
    at Parser.__write (/.../node_modules/csv-parse/lib/index.js:496:14)
    at Parser._transform (/.../node_modules/csv-parse/lib/index.js:182:14)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Parser.Writable.write (_stream_writable.js:243:11)
    at Gunzip.ondata (_stream_readable.js:555:20)
```

If I write out the offending lines, we can see that the failure happens when the line has a length of 152k characters...   I have lines that have more than 10M characters that I need to process. 

```
Logging Statement: logger.write(`${lineCount} (${data.length}): ${data}\n`);

Resulting Log:

27101 (917): 1400566647	USA	0	POLYGON ((-94.54188 33.31186, -94.5419...

27102 (1009): 1400566648	USA	0	POLYGON ((-94.5918 33.29107, -94.59171...

27103 (1255): 1400566649	USA	0	POLYGON ((-94.5849 33.28622, -94.58478...

27104 (285): 1400566796	USA	0	POLYGON ((-96.70757 33.04324, -96.70762...

27105 (1234): 1400566829	CAN	0	POLYGON ((-73.50145 45.86377, -73.50207...

27106 (152408): 1400567785	USA	0	POLYGON ((-73.19229 45.01334, -73.17011...
```

Two questions...  
  * first is just that the error message is misleading...   I guess should be classed as a bug?
  * second, I don't have any control over the incoming dataset, any thoughts on if the csv-parse module should work and how cases like this might be handled?

**Comment by wdavidw** [comment]
There is no limit on the length of a line. You're issue doesn't seem to be related to streaming so u'll need to give a single line producing the error against the following code:

```js
parse = require('csv-parse');
parse(ur_line, { columns: true, auto_parse: false, delimiter: '\t' }, function(err, data){
  console.log(err, data);
})
```

**Comment by wdavidw** [comment]
Doing some cleanup, feel free to re-open a new issue.
