### ISSUE TITLE
TypeError: Invalid data, chunk must be a string or buffer, not object

### ISSUE THREAD

**Issue by AlesMenzel** [adaltas/node-csv-parse#158]
Streaming API bug:
`TypeError: Invalid data, chunk must be a string or buffer, not object`

![](https://image.prntscr.com/image/sQfU1NVfRMS3FFubUHxQCQ.png)

Reproduction:
```js
const fs = require('fs');
const csv = require('csv');

const source = fs.createReadStream('file.csv');
source.on('error', console.log);

const parser = csv.parse({ delimiter: ',' });
parser.on('error', console.log);

source.pipe(parser).pipe(process.stdout);
```

file.csv (utf-8)
```csv
A,B,C
1,2,3
```

Full stacktrace:
```js
TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:696:11)
    at Parser.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Parser.Readable.push (_stream_readable.js:197:10)
    at Parser.Transform.push (_stream_transform.js:151:32)
    at Parser.__push ( ... )
    at Parser.__write ( ... )

... =  path_to_repro_file
```

Node: 8.1.4
csv: 1.1.1

**Comment by wdavidw** [comment]
Normal, the parser take a string and transform it to records in the form of an array or an object while `process.stdout` is only accepting a string or a buffer.

**Comment by AlesMenzel** [comment]
Dumb misstake, thanks. Didnt relalize that.
