### ISSUE TITLE
Error: Number of columns on line 39 does not match header

### ISSUE THREAD

**Issue by ratnam99** [adaltas/node-csv-parse#172]
```
Error: Number of columns on line 39 does not match header
    at Error (native)
    at Parser.__push (/Users/sahusoft/Sites/projects/cloud9pg-api/node_modules/csv-parse/lib/index.js:319:14)
    at Parser.__write (/Users/sahusoft/Sites/projects/cloud9pg-api/node_modules/csv-parse/lib/index.js:562:20)
    at Parser._transform (/Users/sahusoft/Sites/projects/cloud9pg-api/node_modules/csv-parse/lib/index.js:252:14)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at ReadStream.ondata (_stream_readable.js:555:20)
```

This is the error that I'm getting when I try to parse multiple files via loop. Following is my code:-

```
csvFileNameArray.forEach(fileName=>{
    console.log("filename", fileName);
    fs.createReadStream('./public/constants/'+fileName).pipe(parser);
})
```

Here, the csvFileNameArray is a array of filenames. And when I parse those files one at a time by writing the code ```fs.createReadStream(filepath).pipe(parse)``` it parses them without any error. 
Please reply me asap the solution to this problem.

**Comment by ratnam99** [comment]
The thing is, I want to parse multiple .csv files one by one. So, I tried to set the filename to `fs.createReadStream()` via forEach loop. But it makes it async I guess. The callback function is hit only once for all the .csv files. 
I want to ask that Is there any way I can call the callback for each file independently?

**Comment by wdavidw** [comment]
Yes, `fs.createReadStream` will make it async. But async or not, it doesnt explain how you can have a parsing issue by introduction a for loop.

You might be interested by using [each](https://www.npmjs.com/package/each), it will handle the throttling of your file traversal as well as it's async nature. It should looks like:

```
each = require 'each'
parse = require 'csv-parse'
each files
.call (file, callback) ->
  fs.createReadStream file
  .pipe parse options
  .on 'error', callback
  .on 'end', callback
.next (err) ->
  console.log err?.message or 'done'
```

**Comment by ratnam99** [comment]
Thank you @wdavidw, it worked out for me. Also the problem was, that I had defined the parser globally, which created only one instance. But I needed individual instances. So, the problem was fixed by making a new parser everytime for each files.
