### ISSUE TITLE
Test failures on version 2.2.0

### ISSUE THREAD

**Issue by seth-priya** [adaltas/node-csv-parse#187]
Hi,

Observed that there are 2 tests that fail on version 2.2.0. These are related to cast/auto-parse, is it in anyway related to https://github.com/adaltas/node-csv-parse/commit/bd6adeeda0af68acf64e44480d8fc99ab1e5cc14

Are there additional settings required to make these work?

Error log
  147 passing (255ms)
  2 failing

  1) options "auto_parse" (deprecated)
       custom function:

      Uncaught AssertionError: expected Array [
  Array [
    2000-01-01 05:00:00.000 -0000,
    Object { quoting: false, count: 0, index: 1, column: 1 }
  ],
  Array [
    2050-11-27 05:00:00.000 -0000,
    Object { quoting: false, count: 1, index: 1, column: 1 }
  ]
] to equal Array [
  Array [
    2000-01-01 04:00:00.000 -0000,
    Object { quoting: false, count: 0, index: 1, column: 1 }
  ],
  Array [
    2050-11-27 04:00:00.000 -0000,
    Object { quoting: false, count: 1, index: 1, column: 1 }
  ]
] (at '0' -> '0', A has 2000-01-01 05:00:00.000 -0000 and B has 2000-01-01 04:00:00.000 -0000)
      + expected - actual

       [
         [
      -    [Date: 2000-01-01T05:00:00.000Z]
      +    [Date: 2000-01-01T04:00:00.000Z]
           {
             "column": 1
             "count": 0
             "index": 1
             "quoting": false
           }
         ]
         [
      -    [Date: 2050-11-27T05:00:00.000Z]
      +    [Date: 2050-11-27T04:00:00.000Z]
           {
             "column": 1
             "count": 1
             "index": 1

      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.Object.defineProperty.value (node_modules/should/cjs/should.js:356:19)
      at /home/jenkins/node-csv-parse-2.2.0/test/options.auto_parse.coffee:52:22
      at .<anonymous> (src/index.coffee.md:104:18)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) options "cast"
       custom function:

      Uncaught AssertionError: expected Array [
  Array [
    2000-01-01 05:00:00.000 -0000,
    Object { quoting: false, count: 0, index: 1, column: 1 }
  ],
  Array [
    2050-11-27 05:00:00.000 -0000,
    Object { quoting: false, count: 1, index: 1, column: 1 }
  ]
] to equal Array [
  Array [
    2000-01-01 04:00:00.000 -0000,
    Object { quoting: false, count: 0, index: 1, column: 1 }
  ],
  Array [
    2050-11-27 04:00:00.000 -0000,
    Object { quoting: false, count: 1, index: 1, column: 1 }
  ]
] (at '0' -> '0', A has 2000-01-01 05:00:00.000 -0000 and B has 2000-01-01 04:00:00.000 -0000)
      + expected - actual

       [
         [
      -    [Date: 2000-01-01T05:00:00.000Z]
      +    [Date: 2000-01-01T04:00:00.000Z]
           {
             "column": 1
             "count": 0
             "index": 1
             "quoting": false
           }
         ]
         [
      -    [Date: 2050-11-27T05:00:00.000Z]
      +    [Date: 2050-11-27T04:00:00.000Z]
           {
             "column": 1
             "count": 1
             "index": 1

      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.Object.defineProperty.value (node_modules/should/cjs/should.js:356:19)
      at /home/jenkins/node-csv-parse-2.2.0/test/options.cast.coffee:52:22
      at .<anonymous> (src/index.coffee.md:104:18)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Test failed.  See above for more details.

Please suggest, thanks!

Regards,
Priya

**Comment by wdavidw** [comment]
Thank you for noticing, was working on my laptop. I just [remove the notion of date](a9ac638ab6737cdb498f306cb563627a985ade28) in the test which was totally irrelevant.
