### ISSUE TITLE
Unhandled 'error' event : Number of columns is inconsistent on line xxx

### ISSUE THREAD

**Issue by thierryler** [adaltas/node-csv-parse#194]
Hello,

Using version 2.4.0, I get this error when a line is malformed :

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Number of columns is inconsistent on line 370
    at Parser.error (/.../node_modules/csv-parse/lib/index.js:688:9)
    at Parser.__push (/.../node_modules/csv-parse/lib/index.js:333:18)
    at Parser.__write (/.../node_modules/csv-parse/lib/index.js:621:22)
    at Immediate.setImmediate [as _onImmediate] (/.../node_modules/csv-parse/lib/index.js:263:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

My code :
```
const readStream = fs.createReadStream(filePath).pipe(parse({
  delimiter: this.csvDelimiter, 
  skip_lines_with_error: true,    
  skip_empty_lines: true,         
  rtrim: true,          
  trim: true,          
  comment: '#'
}));
```

Why the param skip_lines_with_error does not skip the line ? And how to catch the Unhandled 'error' event ?

Thx,
Th.

**Comment by wdavidw** [comment]
Did you try using relax_column_count?
