### ISSUE TITLE
Cannot cast to `undefined` or `null` in `cast` function

### ISSUE THREAD

**Issue by rschweizer** [adaltas/node-csv-parse#218]
I have a custom `cast` callback function in which I try to cast `''` (empty string) to `undefined` and `'null'` to `null`. After upgrading to `"csv-parse": "^4.0.1"` this is not possible anymore, but fails since `undefined` and `null` have no property `length`. I assume from the error, that this is because `__onField` expects a string.

Custom cast function:
```javascript
function castValue(value, { column: { name }, header }) {
  if (value === '') {
    return undefined
  }

  if (value === 'null') {
    return null
  }

  ...
}
```

Error message:
```bash
TypeError: Cannot read property 'length' of null
    at Parser.__onField (/Volumes/Workspace/lambda-product-feed-service/node_modules/csv-parse/lib/index.js:536:39)
    at Parser.__parse (/Volumes/Workspace/lambda-product-feed-service/node_modules/csv-parse/lib/index.js:360:35)
    at Parser._transform (/Volumes/Workspace/lambda-product-feed-service/node_modules/csv-parse/lib/index.js:195:22)
    at Parser.Transform._read (_stream_transform.js:190:10)
    at Parser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Parser.Writable.write (_stream_writable.js:299:11)
    at ReadStream.ondata (_stream_readable.js:670:20)
    at ReadStream.emit (events.js:182:13)
```

On a side note: The documentation should be updated, since the `context` param passed to `cast(data, context)` now contains a `column` object rather than a string.

**Comment by wdavidw** [comment]
Thank you for your report. Version 4.1.0 shall fix the two issues:
- return value may be null or undefined
- `context.column` is now a string like it was always meant to be
