### ISSUE TITLE
Handling .xls or .xlx files?

### ISSUE THREAD

**Issue by PythonDevOp** [adaltas/node-csv-parse#243]
I was curious, since I couldn't find it explicitly written, if this library supports parsing Excel files such as those with `.xls` or `.xlx` extensions, or if this is only for `.csv` files. Any thoughts?

I have tried to parse `.xls` and it failed with the following:
```
Invalid opening quote at line 3
    at Parser.__error (/Users/User/Documents/my-project/node_modules/csv-parse/lib/index.js:828:17)
    at Parser.__parse (/Users/User/Documents/my-project/node_modules/csv-parse/lib/index.js:462:34)
    at Parser._transform (/Users/User/Documents/my-project/node_modules/csv-parse/lib/index.js:340:22)
    at Parser.Transform._read (_stream_transform.js:186:10)
    at Parser.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Parser.Writable.write (_stream_writable.js:290:11)
    at parse (/Users/User/Documents/my-project/node_modules/csv-parse/lib/index.js:875:12)
```
**Edit - Adding a snippet of the Node.JS server code that reads the file, and parses it**

```
const csvParser = require("csv-parse");
let filePath = req.file.path;

const theFile = fs.readFileSync(filePath, "utf8").toString();

csvParser(theFile, { columns: true }, function(err, rows) {
    if (err) {
       console.log("CSV Parser Error: ", err);
       return res.status(500).send({ message: "Error with the file" });
    } else{
     // do something
    }
}

```

If it is not supported, that is fine. I just would like to find out one way or the other! Thanks!

**Comment by wdavidw** [comment]
I haven't personally tried.

**Comment by PythonDevOp** [comment]
I am uploading a file to a Node.js server, and having the csv-parse library. I just added some additional context with a code snippet.
Would you be able to at least provide guidance as to why something might fail with the above error message? The same data works when presented as a `.csv` file but fails as `.xls`.

Perhaps would it have to do with the `fs.readFileSync` option which is set as `utf8`?

**Comment by wdavidw** [comment]
What I can garanty you is that both `fs.readFileSync` and the csv-parse package are agnostic of the file extension. Ensure that the checksum of your 2 files, `.csv` and `.xls` are identical.
