### ISSUE TITLE
Version 4.6.0 is buggy

### ISSUE THREAD

**Issue by gcampax** [adaltas/node-csv-parse#258]
Greenkeeper on our CI made me notice the following error with version 4.6.0:

> /home/travis/build/stanford-oval/almond-cloud/node_modules/csv-parse/lib/index.js:955
    for(context of contexts){
        ^
ReferenceError: context is not defined
    at new CsvError (/home/travis/build/stanford-oval/almond-cloud/node_modules/csv-parse/lib/index.js:955:9)
    at Parser.__onRow (/home/travis/build/stanford-oval/almond-cloud/node_modules/csv-parse/lib/index.js:625:15)
    at Parser.__parse (/home/travis/build/stanford-oval/almond-cloud/node_modules/csv-parse/lib/index.js:527:40)
    at Parser._flush (/home/travis/build/stanford-oval/almond-cloud/node_modules/csv-parse/lib/index.js:352:22)
    at Parser.prefinish (_stream_transform.js:141:10)
    at Parser.emit (events.js:198:13)
    at prefinish (_stream_writable.js:635:14)
    at finishMaybe (_stream_writable.js:643:5)
    at endWritable (_stream_writable.js:663:3)
    at Parser.Writable.end (_stream_writable.js:594:5)

I have pinned to 4.5.0 for now, but I would be nice to have the latest version fixed. Thanks!

**Comment by wdavidw** [comment]
I've release 4.6.1, which looks like

```js
    for(const context of contexts){
      for(const key in context){
```

Let me know if that fix your issue. Also, how did you run your tests to catch up this issue, I'll be happy to add the settings in mine.

**Comment by gcampax** [comment]
The tests we use are tests of our software, that just happens to use csv-parse. We use [Greenkeeper](https://greenkeeper.io) to run the CI every time a new dep update occurs, and then the bot automatically opens an issue when the CI starts failing due to a dep.
I am not familiar with this code, but I suspect a CI that runs lint or unit tests could help?
