### ISSUE TITLE
Invalid opening quote, even if working in the online converter

### ISSUE THREAD

**Issue by marcells** [adaltas/node-csv-parse#300]
**Describe the bug**

I try parsing a CSV file with the sync library of `csv-parser`.

The following error is thrown:
```
Error: Invalid Opening Quote: a quote is found inside a field at line 1
    at Parser.__parse (C:\dev\corona-scrape\node_modules\csv-parse\lib\index.js:553:19)
    at module.exports (C:\dev\corona-scrape\node_modules\csv-parse\lib\sync.js:20:23)
```

While trying exactly the same data with https://csv.js.org/convert/ and setting (see below) everything is parsed as expected.

**To Reproduce**

1. [Download](https://www.umweltbundesamt.de/api/air_data/v2/measures/csv?date_from=2020-09-26&time_from=24&date_to=2020-10-30&time_to=24&data%5B0%5D%5Bco%5D=1&data%5B0%5D%5Bsc%5D=1&data%5B0%5D%5Bda%5D=2020-10-30&data%5B0%5D%5Bti%5D=13&data%5B0%5D%5Bst%5D=216&data%5B0%5D%5Bva%5D=8&data%5B1%5D%5Bco%5D=1&data%5B1%5D%5Bsc%5D=1&data%5B1%5D%5Bda%5D=2020-10-30&data%5B1%5D%5Bti%5D=12&data%5B1%5D%5Bst%5D=299&data%5B1%5D%5Bva%5D=11&data%5B2%5D%5Bco%5D=1&data%5B2%5D%5Bsc%5D=1&data%5B2%5D%5Bda%5D=2020-10-30&data%5B2%5D%5Bti%5D=12&data%5B2%5D%5Bst%5D=220&data%5B2%5D%5Bva%5D=8&data%5B3%5D%5Bco%5D=1&data%5B3%5D%5Bsc%5D=1&data%5B3%5D%5Bda%5D=2020-10-30&data%5B3%5D%5Bti%5D=12&data%5B3%5D%5Bst%5D=221&data%5B3%5D%5Bva%5D=7&lang=de) the data set

Extract of the first rows:
```
"Bundesland / Messnetz";Stationscode;Stationsname;Stationsumgebung;"Art der Station";Schadstoff;"Art der Auswertung";Datum;Uhrzeit;Messwert;Einheit
Baden-Württemberg;DEBW005;Mannheim-Nord;"vorstädtisches Gebiet";Industrie;"Feinstaub (PM₁₀)";"Tagesmittel (1TMW)";27.09.2020;-;3;µg/m³
Baden-Württemberg;DEBW005;Mannheim-Nord;"vorstädtisches Gebiet";Industrie;"Feinstaub (PM₁₀)";"Tagesmittel (1TMW)";28.09.2020;-;7;µg/m³
Baden-Württemberg;DEBW005;Mannheim-Nord;"vorstädtisches Gebiet";Industrie;"Feinstaub (PM₁₀)";"Tagesmittel (1TMW)";29.09.2020;-;9;µg/m³
```

2. Try to parse with the following parser options

```
{
    cast: true,
    columns: true,
    delimiter: ';',
    relaxColumnCount: true,
    skipEmptyLines: true,
}
```

Code sample:

```
import got from 'got';
import parse from "csv-parse/lib/sync.js";

(async function () {
  const airDataUrl = 'https://www.umweltbundesamt.de/api/...'; // Link from above
  const response = await got(airDataUrl);
  const csvData = response.body;

  console.log(csvData);

  const airData = parse(csvData, {
    cast: true,
    columns: true,
    delimiter: ';',
    relaxColumnCount: true,
    skipEmptyLines: true,
  })
})();
```

**Comment by marcells** [comment]
Forget about it. I did forget the `bom: true` option. 🤦‍♂️
