### ISSUE TITLE
Whitespace at the end of a row

### ISSUE THREAD

**Issue by Perlence** [adaltas/node-csv-parse#36]
If last value of row is quoted followed by whitespace, parser throws error `Invalid closing quote`:

``` js
> parse = require('csv-parse')
> parse('a,b\n"1","2" \n"3","4"', function(err) { console.error(err.stack); })
Error: Invalid closing quote at line 2; found " " instead of delimiter ","
    at Parser.__write (/home/ubuntu/workspace/node_modules/csv-parse/lib/index.js:249:19)
    at Parser._transform (/home/ubuntu/workspace/node_modules/csv-parse/lib/index.js:138:10)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Writable.write (_stream_writable.js:183:11)
    at repl:1:14
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
```

`trim` option doesn't do anything about it, although `relax` seems to handle this somehow, but value is left unquoted:

``` js
> parse('a,b\n"1","2" \n"3","4"', {relax: true}, console.log)
null [ [ 'a', 'b' ], [ '1', '"2" ' ], [ '3', '4' ] ]
```

**Comment by wdavidw** [comment]
i'm not surprise with relax, this is the exepected behavior. considering space around quote, it would make sense but this is not an easy task considering how the parser is written and i dont have the time to dig it

**Comment by wdavidw** [comment]
Doing some house cleaning. There has been some dev since this issue around "relax" and "trim" options. Feel free to open a new issue if needed.
